
services:
  redis:
    image: redis:7-alpine
    expose:
      - "6379"
  app:
    build:
      context: ./backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started